export interface PhysicalFoundation {
  id: string;
  number: number;
  title: string;
  description: string;
  icon: string;
  status: 'completed' | 'current' | 'locked';
  lessons: PhysicalLesson[];
}

export interface PhysicalLesson {
  id: string;
  title: string;
  description: string;
  type: 'education' | 'practice' | 'assessment';
  status: 'completed' | 'current' | 'locked';
  xp: number;
  estimatedTime: number;
}

// 10 Foundations x 3 Lessons = 30 Total Lessons
export const PHYSICAL_FOUNDATIONS: PhysicalFoundation[] = [
  {
    id: 'foundation1',
    number: 1,
    title: 'Understanding Holistic Health',
    description: 'Learn what holistic health means and how body systems connect',
    icon: '🌟',
    status: 'current',
    lessons: [
      {
        id: 'foundation1-lesson1',
        title: 'What is Holistic Health?',
        description: 'Four pillars of wellness: physical, mental, emotional, lifestyle',
        type: 'education',
        status: 'current',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation1-lesson2',
        title: 'Your Body is a System',
        description: 'The gut-brain connection and interconnected health',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation1-lesson3',
        title: 'Prevention Over Treatment',
        description: 'Daily habits that protect your long-term health',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
    ],
  },
  {
    id: 'foundation2',
    number: 2,
    title: 'Sleep and Recovery',
    description: 'Master sleep for energy, healing, and mental clarity',
    icon: '😴',
    status: 'locked',
    lessons: [
      {
        id: 'foundation2-lesson1',
        title: 'Why Sleep is Your Superpower',
        description: 'What happens during sleep and why it matters',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation2-lesson2',
        title: 'The Circadian Rhythm',
        description: 'Your body\'s internal clock and how to support it',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation2-lesson3',
        title: 'Sleep Hygiene Basics',
        description: 'Create the perfect sleep environment and routine',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation3',
    number: 3,
    title: 'Stress and Inflammation',
    description: 'Manage stress and reduce chronic inflammation',
    icon: '🧘',
    status: 'locked',
    lessons: [
      {
        id: 'foundation3-lesson1',
        title: 'Stress: The Silent Killer',
        description: 'How chronic stress damages your health',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation3-lesson2',
        title: 'Inflammation: Friend or Foe?',
        description: 'Signs of chronic inflammation and how to reduce it',
        type: 'assessment',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation3-lesson3',
        title: 'Simple Stress Management Tools',
        description: '5-10 minute daily practices for stress relief',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation4',
    number: 4,
    title: 'Nutrition Fundamentals',
    description: 'Use food as medicine for optimal health',
    icon: '🥗',
    status: 'locked',
    lessons: [
      {
        id: 'foundation4-lesson1',
        title: 'Food as Medicine',
        description: 'The microbiome and how food impacts your cells',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation4-lesson2',
        title: 'The Truth About Sugar',
        description: 'Hidden sugars and their impact on health',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation4-lesson3',
        title: 'Building a Balanced Plate',
        description: 'The plate method for every meal',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation5',
    number: 5,
    title: 'Movement and Exercise',
    description: 'Find movement you enjoy and build consistency',
    icon: '🏃',
    status: 'locked',
    lessons: [
      {
        id: 'foundation5-lesson1',
        title: 'You Were Born to Move',
        description: 'Exercise benefits and why sitting is harmful',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation5-lesson2',
        title: 'The Best Exercise is the One You\'ll Do',
        description: 'Four types of exercise for complete fitness',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation5-lesson3',
        title: 'Recovery is Part of Training',
        description: 'Rest days and active recovery strategies',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation6',
    number: 6,
    title: 'Preventive Health Screenings',
    description: 'Catch problems early with regular health checks',
    icon: '🩺',
    status: 'locked',
    lessons: [
      {
        id: 'foundation6-lesson1',
        title: 'Prevention Saves Lives',
        description: 'Essential health screenings by age',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation6-lesson2',
        title: 'Know Your Numbers',
        description: 'Blood pressure, cholesterol, blood sugar basics',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation6-lesson3',
        title: 'Build a Relationship with Your Doctor',
        description: 'Questions to ask and how to advocate for yourself',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation7',
    number: 7,
    title: 'Gut Health and Digestion',
    description: 'Heal your gut for better mood, immunity, and energy',
    icon: '🦠',
    status: 'locked',
    lessons: [
      {
        id: 'foundation7-lesson1',
        title: 'Your Gut is Your Second Brain',
        description: 'The microbiome and gut-brain connection',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation7-lesson2',
        title: 'Feeding Your Good Bacteria',
        description: 'Gut-healing foods and microbiome diversity',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation7-lesson3',
        title: 'Parasites and Gut Health',
        description: 'Signs of parasites and when to get tested',
        type: 'assessment',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation8',
    number: 8,
    title: 'Hormones and Balance',
    description: 'Balance hormones for energy, mood, and metabolism',
    icon: '⚖️',
    status: 'locked',
    lessons: [
      {
        id: 'foundation8-lesson1',
        title: 'Hormones Control Everything',
        description: 'Key hormones and the domino effect',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation8-lesson2',
        title: 'Blood Sugar and Insulin',
        description: 'Insulin resistance and how to stabilize blood sugar',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation8-lesson3',
        title: 'Supporting Hormonal Balance',
        description: 'Lifestyle changes for hormone health',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation9',
    number: 9,
    title: 'Hydration and Detox',
    description: 'Support your body\'s natural detoxification systems',
    icon: '💧',
    status: 'locked',
    lessons: [
      {
        id: 'foundation9-lesson1',
        title: 'Water is Life',
        description: 'Signs of dehydration and how much to drink',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation9-lesson2',
        title: 'Your Liver: The Detox Powerhouse',
        description: 'How the liver detoxifies and foods that support it',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation9-lesson3',
        title: 'Do You Need to "Detox"?',
        description: 'Debunking detox myths and reducing toxin exposure',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
  {
    id: 'foundation10',
    number: 10,
    title: 'Mindset and Long-Term Success',
    description: 'Build sustainable health habits for life',
    icon: '🎯',
    status: 'locked',
    lessons: [
      {
        id: 'foundation10-lesson1',
        title: 'Health is a Journey, Not a Destination',
        description: 'The 80/20 rule and building systems',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation10-lesson2',
        title: 'Your Health, Your Responsibility',
        description: 'Take ownership and the compound effect',
        type: 'education',
        status: 'locked',
        xp: 50,
        estimatedTime: 5,
      },
      {
        id: 'foundation10-lesson3',
        title: 'Celebrate Your Progress',
        description: 'Non-scale victories and completing your health path',
        type: 'practice',
        status: 'locked',
        xp: 50,
        estimatedTime: 6,
      },
    ],
  },
];
